# suggestions.py

skill_tips = {
    "python": "Learn Python basics at W3Schools or freeCodeCamp.",
    "java": "Practice Java on HackerRank or CodeGym.",
    "c++": "Explore C++ tutorials on GeeksforGeeks.",
    "html": "Learn HTML with W3Schools interactive guide.",
    "css": "Use CSS Flexbox and Grid on freeCodeCamp.",
    "javascript": "Build small projects using JavaScript on JSFiddle.",
    "sql": "Practice SQL queries on LeetCode or SQLZoo.",
    "mongodb": "Explore MongoDB University free courses.",
    "mysql": "Practice MySQL commands using W3Schools SQL editor.",
    "git": "Use GitHub and learn Git via Codecademy Git course.",
    "github": "Learn version control with GitHub via official docs.",
    "flask": "Build a mini Flask app using the Flask official docs.",
    "django": "Follow Django Girls Tutorial or RealPython articles.",
    "machine learning": "Start the Machine Learning course by Andrew Ng on Coursera.",
    "deep learning": "Explore TensorFlow tutorials and Keras examples.",
    "data science": "Do hands-on projects using Kaggle datasets.",
    "nlp": "Use NLTK and spaCy to do basic text analysis.",
    "pandas": "Solve data cleaning tasks with pandas on Kaggle.",
    "numpy": "Understand NumPy arrays using W3Schools or NumPy docs.",
    "matplotlib": "Learn to plot charts using Matplotlib official guide.",
    "data visualization": "Use Seaborn or Plotly for interactive plots.",
    "excel": "Practice formulas and pivot tables via ExcelJet.",
    "power bi": "Create dashboards using Microsoft Power BI tutorials.",
    "tableau": "Follow Tableau public tutorials and sample projects.",
    "rest api": "Create and test REST APIs using Postman.",
    "postman": "Explore Postman learning center for API testing.",
    "oop": "Understand Object-Oriented Programming principles via Java or Python.",
    "data structures": "Practice DSA on LeetCode, GeeksforGeeks.",
    "algorithms": "Take an Algorithms course from Princeton on Coursera.",
    "problem solving": "Solve daily coding challenges on HackerRank or Codeforces.",
    "communication": "Improve verbal skills through TED Talks and speaking clubs.",
    "teamwork": "Work on group projects or participate in hackathons.",
    "leadership": "Lead a small team in events or project submissions.",
    "creativity": "Build personal projects to apply your creative thinking.",
    "cloud computing": "Start with AWS free tier and tutorials.",
    "aws": "Complete AWS Cloud Practitioner Essentials course.",
    "azure": "Use Microsoft Learn to explore Azure basics.",
    "google cloud": "Take the GCP Fundamentals course from Qwiklabs.",
    "linux": "Practice Linux commands on Ubuntu or LinuxShellTips.",
    "bash": "Automate tasks using Bash scripting basics.",
    "cybersecurity": "Take basic cybersecurity modules from Cisco NetAcad.",
    "networking": "Understand OSI model and IP routing basics.",
    "operating systems": "Learn concepts like processes, memory from Neso Academy.",
    "debugging": "Debug using print statements and IDE tools.",
    "testing": "Write unit tests in Python using `unittest` or `pytest`.",
    "software engineering": "Follow SDLC phases and agile methodology.",
    "agile": "Understand scrum process and agile roles.",
    "ui/ux design": "Explore Figma and basic design principles.",
    "responsive design": "Use Bootstrap or media queries for mobile-first layouts.",
    "presentation": "Improve presentation skills via practice and video feedback."
}
